import { toNano, beginCell, Address, SendMode, fromNano } from '@ton/core';
import { buildJettonMinterFromEnv, content, envContent } from '../utils/jetton-helpers';
import { FossFiConfig, MintNewJettons, storeMint } from '../wrappers/fi/FossFi';
import { getJettonHttpLink, getNetworkFromEnv } from '../utils/utils';
import { printSeparator } from '../utils/print';
import "dotenv/config";

import { FossFi } from '../wrappers/fi/FossFi';
import { compile, NetworkProvider } from '@ton/blueprint';

export async function run(provider: NetworkProvider) {
    const deployer = process.env.DEPLOYER;
    if (deployer === undefined) {
        console.error("deployer address is not provided, please add it to .env file")
        throw new Error("deployer address is not provided")
    }
    const deployerAddress = Address.parse(deployer);
    const supply = toNano(process.env.JETTON_SUPPLY ?? 1000000000) // 1_000_000_000 jettons
    const deployAmount = toNano("0.5");
    // const fossFi = provider.open(await buildJettonMinterFromEnv(deployerAddress));

    // ====================================================================================
    const walletCode = await compile('FossFiWallet')

    const fossFiConfig: FossFiConfig = {
        admin_address: deployerAddress,
        base_fi_wallet_code: walletCode,
        metadata_uri: envContent // content
    };
    
    const fossFi = provider.open(FossFi.createFromConfig(fossFiConfig, await compile('FossFi')));

    // FIXME deploy first by sending init and value
    const mint = {
        $$type: "MintNewJettons",
        queryId: 0n,
        mintRecipient: deployerAddress,
        tonAmount: toNano("0.2"),
        internalTransferMsg: {
            $$type: "InternalTransferStep",
            queryId: 0n,
            jettonAmount: supply,
            version: 0n, // todo: txn mightFailOnFurtherMints coz jettonWallet's different
            transferInitiator: deployerAddress,
            sendExcessesTo: deployerAddress,
            forwardTonAmount: 0n,
            forwardPayload: beginCell().storeUint(0, 1).asSlice(),
        },
    } as MintNewJettons;

    // await fossFi.sendDeploy(provider.sender(), toNano('0.05'));

    // await provider.waitForDeploy(fossFi.address);

    // run methods on `fossFi`==============================================================
    

    await provider.sender().send(
        {
            value: deployAmount,
            to: fossFi.address,
            sendMode: SendMode.PAY_GAS_SEPARATELY, // + SendMode.IGNORE_ERRORS,
            // bounce: true,
            init: fossFi.init,
            body: beginCell()
                .store(
                    storeMint(mint),
                )
                .endCell(),
        }
    )

    // await fossFi.send(
    //     provider.sender(),
    //     {
    //         value: deployAmount,
    //         bounce: true,
    //     },
    //     mint,
    // );

    const network = getNetworkFromEnv()
    console.log(`Running deploy script for ${network} network and for Shard Jetton Minter`)
    console.log(
        "Make sure to send txn from following wallet:. \n" +
        deployerAddress.toString({testOnly: true})
    )
    printSeparator()
    console.log("Minting:: ", fromNano(supply))
    printSeparator()

    try {
        const fs = await import("fs/promises")
        const outFile = `${process.cwd()}/scripts/consts.ts`
        const address = fossFi.address.toString()
        const content = `// Auto-generated by shard.deploy.ts\nexport const FI_ADDRESS = "${address}"\n`
        await fs.writeFile(outFile, content, "utf8")
        console.log("Saved fossFi address const to", outFile)
    } catch (err) {
        console.warn("Failed to save fossFi address:", err)
    }
    const link = getJettonHttpLink(network, fossFi.address, "tonviewer")
    console.log(`You can soon check your deployed contract at ${link}`)

    // await provider.waitForDeploy(fossFi.address, 3, 30000);
    console.log(`Jetton Minter deployed successfully!`);
    // run methods on `dns`
}
